---

- hosts: all
  become: true
  roles:
    - role: general
      tags: always
      hostname: "{{ hostname }}"

    - role: users
      tags: always
      username: "{{ username }}"

    - role: podman
      tags: always
      username: "{{ username }}"

    - role: borg
      tags: backuped
      repository: "{{ borg_repository }}"
      passphrase: "{{ borg_passphrase }}"

    - role: syncthing
      tags: private
