---

- name: Installing necessary packages
  community.general.pacman: name=wireguard-tools

- name: Writing /etc/wireguard/wgvpn0.conf configuration file.
  ansible.builtin.template:
    src: wgvpn0.conf.j2
    dest: /etc/wireguard/wgvpn0.conf
    mode: 0600
  notify: Restarting wg-quick@wgvpn0 service

- ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
